In [ ]:
import pandas as pd
import numpy as np

upload the data

In [ ]:
df = pd.read_csv("/content/pluscbdoil.com_update.csv")

In [ ]:
df.head()

Unnamed: 0       Product_Name  Ratings  Cost($)  Review
0           0   CBD Calm Gummies      5.0    29.99     3.0
1           1   CBD Calm Gummies      4.2    29.99    14.0
2           2  CBD Sleep Gummies      5.0    29.99    52.0
3           3  CBD Sleep Gummies      4.8    29.99    41.0
4           4           CBD BALM      4.7    29.99    68.0

In [ ]:
df.columns

Index(['Unnamed: 0', 'Product_Name', 'Ratings', 'Cost($)', 'Review'], dtype='object')

In [ ]:
#rename the column
df.rename(columns = {'Product_Name':'Name'}, inplace = True)

In [ ]:
df.columns

Index(['Unnamed: 0', 'Name', 'Ratings', 'Cost($)', 'Review'], dtype='object')

In [ ]:
#remove unused column
df.drop('Unnamed: 0', inplace=True, axis=1)

In [ ]:
df['Ratings'].unique()

array([5. , 4.2, 4.8, 4.7, 4.6, 4.9, nan])

In [ ]:
df['Cost($)'].unique()

array([ 29.99,  79.99,  39.99,  27.99, 119.99,  31.99,  47.98, 159.99,
       139.99,  24.99,  19.99,  54.99, 107.99,  59.99,  95.98,  14.99,
        61.58])

In [ ]:
df['Review'].unique()

array([ 3., 14., 52., 41., 68., 76., 10., 61.,  2.,  1., 54., 22.,  8.,
        4.,  7., nan])

In [ ]:
#fill the nan values for whole data set using pandas
df1 = df.fillna(0)

In [ ]:
df = pd.DataFrame(df1)

In [ ]:
df.head(5)

Name  Ratings  Cost($)  Review
0   CBD Calm Gummies      5.0    29.99     3.0
1   CBD Calm Gummies      4.2    29.99    14.0
2  CBD Sleep Gummies      5.0    29.99    52.0
3  CBD Sleep Gummies      4.8    29.99    41.0
4           CBD BALM      4.7    29.99    68.0

generate new csv file using previous file

In [ ]:
df.to_csv("pluscbdoil.com_new.csv")

In [ ]:
data = pd.read_csv("/content/pluscbdoil.com_new.csv")

In [ ]:
data.columns

Index(['Unnamed: 0', 'Name', 'Ratings', 'Cost($)', 'Review'], dtype='object')

In [ ]:
df = pd.DataFrame(data=data)

In [ ]:
df['Ratings'].unique()

array([5. , 4.2, 4.8, 4.7, 4.6, 4.9, 0. ])

In [ ]:
df['Cost($)'].unique()

array([ 29.99,  79.99,  39.99,  27.99, 119.99,  31.99,  47.98, 159.99,
       139.99,  24.99,  19.99,  54.99, 107.99,  59.99,  95.98,  14.99,
        61.58])

In [ ]:
df['Review'].unique()

array([ 3., 14., 52., 41., 68., 76., 10., 61.,  2.,  1., 54., 22.,  8.,
        4.,  7.,  0.])

In [ ]:
df.columns

Index(['Unnamed: 0', 'Name', 'Ratings', 'Cost($)', 'Review'], dtype='object')

In [ ]:
#remove unused column
df.drop('Unnamed: 0', inplace=True, axis=1)

In [ ]:
df.head()

Name  Ratings  Cost($)  Review
0   CBD Calm Gummies      5.0    29.99     3.0
1   CBD Calm Gummies      4.2    29.99    14.0
2  CBD Sleep Gummies      5.0    29.99    52.0
3  CBD Sleep Gummies      4.8    29.99    41.0
4           CBD BALM      4.7    29.99    68.0

In [ ]:
#how to find max rating
df.Ratings.max()

5.0

In [ ]:
df.Review.max()

76.0

In [ ]:
meanvote = df.Ratings.mean()
meanvote

4.280769230769231

In [ ]:
minimumvote = df.Review.quantile(0.90)
minimumvote

60.29999999999999

In [ ]:
q_products = df.copy().loc[df['Review'] >= minimumvote]
q_products.shape

(6, 4)

In [ ]:
def weighted_ratios(x,minimumvote = minimumvote , meanvote = meanvote):
    voter = x['Review']
    avg_vote = x['Ratings']
    
    return (voter/(voter+minimumvote) * avg_vote ) + (minimumvote/(minimumvote + voter)*meanvote)

In [ ]:
q_products['score'] = q_products.apply(weighted_ratios,axis=1)

In [ ]:
#q_products

In [ ]:
q_products.sort_values('score',ascending=False)

Name  ...     score
4                                            CBD BALM  ...  4.502965
27               CBD SOFTGEL CAPSULES 5MG RAW FORMULA  ...  4.502965
7   CBD SOFTGEL CAPSULES 50MG MAXIMUM STRENGTH FOR...  ...  4.491594
30                                       CBD ROLL-ONS  ...  4.491594
5                                            CBD BALM  ...  4.458770
28                                 CBD STARTER BUNDLE  ...  4.458770

[6 rows x 5 columns]

In [ ]:
pd.set_option('precision',2)

In [ ]:
def recommendation_table(csv):
    df = pd.read_csv(csv)
    meanvote = df.Ratings.mean()
    minimumvote = df.Review.quantile(.2) 
    q_products = df.copy().loc[df['Review'] >= minimumvote]
    q_products['score'] = q_products.apply(weighted_ratios,axis=1)
    print(csv + " Website")
    q_products = q_products.sort_values('score',ascending=False)
    q_products.to_csv(csv + 'Recommended_scores.csv')
def weighted_ratios(x,minimumvote = minimumvote , meanvote = meanvote):
    voter = x['Review']
    avg_vote = x['Ratings']
    
    return (voter/(voter+minimumvote) * avg_vote ) + (minimumvote/(minimumvote + voter)*meanvote)

In [ ]:
recommendation_table('/content/pluscbdoil.com_new.csv')

/content/pluscbdoil.com_new.csv Website


In [ ]:
websites = ["/content/pluscbdoil.com_new.csv","/content/lordjones.csv","/content/Diamondcbd.csv","/content/cbdfx (2).csv","/content/cbdistillery_new.csv"]

In [ ]:
for website in websites:
  recommendation_table(website)

/content/pluscbdoil.com_new.csv Website
/content/lordjones.csv Website
/content/Diamondcbd.csv Website
/content/cbdfx (2).csv Website
/content/cbdistillery_new.csv Website


In [ ]:
websites_recom = ["/content/pluscbdoil.com_new.csvRecommended_scores.csv","/content/lordjones.csvRecommended_scores.csv","/content/Diamondcbd.csvRecommended_scores.csv","/content/cbdfx (2).csvRecommended_scores.csv","/content/cbdistillery_new.csvRecommended_scores.csv"]

In [ ]:
word='oil'
q_products[q_products.Name.astype(str).str.contains(word.title())]

Empty DataFrame
Columns: [Name, Ratings, Cost($), Review, score]
Index: []

In [ ]:
def contains(csv,word):
    df = pd.read_csv(csv)
    display(df[df.Name.astype(str).str.contains(word.title())])

In [ ]:
word = input("Enter your word to search product -> ")
for website in websites_recom:
    print(website)
    print("----------------")
    contains(website,word)

Enter your word to search product -> oil
/content/pluscbdoil.com_new.csvRecommended_scores.csv
----------------


Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, Name, Ratings, Cost($), Review, score]
Index: []

/content/lordjones.csvRecommended_scores.csv
----------------


Unnamed: 0  Unnamed: 0.1  ... Review  score
3           17            17  ...     29   4.42
18          19            19  ...      3   4.30
26          18            18  ...      4   4.28
44           2             2  ...      0   4.28

[4 rows x 7 columns]

/content/Diamondcbd.csvRecommended_scores.csv
----------------


Unnamed: 0  Unnamed: 0.1  ... Review  score
3            85            85  ...    251   4.80
4            59            59  ...    384   4.80
10           19            19  ...    444   4.76
16           11            11  ...    177   4.72
19          157           157  ...    180   4.71
..          ...           ...  ...    ...    ...
580         489           489  ...      0   4.28
587         488           488  ...      0   4.28
593         494           494  ...      0   4.28
594         495           495  ...      0   4.28
605         538           538  ...      1   4.28

[64 rows x 7 columns]

/content/cbdfx (2).csvRecommended_scores.csv
----------------


Unnamed: 0  ...  score
3            9  ...   4.81
18          36  ...   4.74
23          48  ...   4.71
25          50  ...   4.70
26          51  ...   4.70
29          49  ...   4.64
44          52  ...   4.31
56           6  ...   4.27

[8 rows x 8 columns]

/content/cbdistillery_new.csvRecommended_scores.csv
----------------


Unnamed: 0  Unnamed: 0.1  ... Review  score
0           19            19  ...    546   4.75
4           27            27  ...    173   4.67
10           7             7  ...     79   4.58
12          20            20  ...     92   4.53
15          26            26  ...     50   4.52
17           0             0  ...   3324   4.50
18           2             2  ...   1864   4.49
20           9             9  ...    375   4.47
28          30            30  ...     41   4.41
30           1             1  ...   1865   4.40
35          31            31  ...    389   4.38
36          22            22  ...    170   4.37
38          42            42  ...      9   4.36
39          36            36  ...      9   4.35
40          25            25  ...     67   4.34
53          53            53  ...      2   4.28
55          45            45  ...     34   4.25

[17 rows x 7 columns]